### ISSUE TITLE
Create new Logo

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/Twitchcrumbs#4]
You're featured on the front page of CurseForge

gotta make a good impression

**Comment by MrJimmK** [comment]
![Twitchcrumbs](https://user-images.githubusercontent.com/50204878/57091406-65b4ed00-6d09-11e9-87fa-9b95143610df.png)

There you go.

Let me know if i missed something.

**Comment by Skydragonsz** [comment]
I'm not really sure if this is in line with the [Twitch Brand Guidelines](https://www.twitch.tv/p/brand/) (but neither does the current one...)!
Otherwise it looks great.
 

Need to look it up some other time if its fine to use!

**Comment by BlayTheNinth** [comment]
The "Crumbs" part is hard to read when it's downsized and the credits I'd rather put in text somewhere than have them integrated in the icon. Thanks for the attempt so far though!

![image](https://user-images.githubusercontent.com/1933180/57184875-95f3bb80-6ec2-11e9-85c0-3b1b62f7e6f6.png)

![image](https://user-images.githubusercontent.com/1933180/57184876-9a1fd900-6ec2-11e9-858a-db241d3d0b36.png)

**Comment by MrJimmK** [comment]
Gave the "crumbs" part more size and removed the credits.
@Skydragonsz The Twitch brand guidelines only restrict someone to use black or white with their purple :P So I'm sure it'll be fine that way.

I'm happy that the icon itself meets your expectations @blay09 ! As said, i updated the logo based on your feedback. As you stated, a good impression is the goal of this little logo 😁

![Twitchcrumbs](https://user-images.githubusercontent.com/50204878/57194878-57a2de80-6f4c-11e9-94a1-c149e8e2dd8b.png)

**Comment by BlayTheNinth** [comment]
Thanks again for helping with the logo. However, I've decided to rename the mod and created a new logo along with it, without the word "Twitch" in the name. 

That way it doesn't look as if it's officially endorsed by Twitch or, with the upcoming CurseForge Twitchification, won't look like an out-of-place false Twitch logo.
